[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 10
numReplicas = 1

[service]
healthCheckInterval = 60
healthCheckTimeout = 10
